//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NecesidadesDonacionesMonetarias
    {
        public int IdNecesidadDonacionMonetaria { get; set; }
        public int IdNecesidad { get; set; }
        public decimal Dinero { get; set; }
        public string CBU { get; set; }
    
        public virtual DonacionesMonetarias DonacionesMonetarias { get; set; }
        public virtual Necesidades Necesidades { get; set; }
    }
}
