//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NecesidadesDonacionesInsumos
    {
        public int IdNecesidadDonacionInsumo { get; set; }
        public int IdNecesidad { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual DonacionesInsumos DonacionesInsumos { get; set; }
    }
}
