//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TpPrograWebDB : DbContext
    {
        public TpPrograWebDB()
            : base("name=TpPrograWebDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Denuncia> Denuncias { get; set; }
        public virtual DbSet<DonacionesInsumo> DonacionesInsumos { get; set; }
        public virtual DbSet<DonacionesMonetaria> DonacionesMonetarias { get; set; }
        public virtual DbSet<MotivoDenuncia> MotivoDenuncias { get; set; }
        public virtual DbSet<Necesidade> Necesidades { get; set; }
        public virtual DbSet<NecesidadesDonacionesInsumo> NecesidadesDonacionesInsumos { get; set; }
        public virtual DbSet<NecesidadesDonacionesMonetaria> NecesidadesDonacionesMonetarias { get; set; }
        public virtual DbSet<NecesidadesReferencia> NecesidadesReferencias { get; set; }
        public virtual DbSet<NecesidadesValoracione> NecesidadesValoraciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
